### ISSUE TITLE
Is it possible to limit the year?

### ISSUE THREAD

**Issue by TeddJohnson** [LeoKotschenreuther/cryptocoin-tax#1]
Given the way taxes are calculated, is it possible to limit this by year?

I've also tried submitting a CSV, but it registered as 0, so maybe give an example of what format it's excepting?

**Comment by LeoKotschenreuther** [comment]
Hi @JawnZ,
the project doesn't support limiting by year.
I stopped development on this when I realized that there are already some products available that can do a lot more than this project can do right now for a fairly small price.

You are welcome to contribute if you are interested but I don't have any plans to work on this project soon.

Let me know if you want to hear about who offers similar software (some is even for free).

**Comment by csinko** [comment]
Hi @LeoKotschenreuther,
I am interested in other software (namely free) that can also calculate taxes.  I searched around for a bit and this was the only one I could find that seemed to support bittrex.

**Comment by LeoKotschenreuther** [comment]
I came across Bitcoin.tax and cointracking.info that both support imports from Bittrex. However they both have a transaction limit per year in the free version.

I don't think that anybody offers a website to calculate the proceeds on tons of transactions for free. So if you only make a few transactions per year (say less than 100-200) then you can probably get by with a free version. If you make more than a few 100 transactions per year then I hope you make so much money that you can afford to pay a little bit for the tax software.
